language: csharp
mono: none
sudo: required
dist: bionic
dotnet: 3.1
services:
- docker
script:
- cd src/SpikeCore
- dotnet restore
- dotnet build -c Release
- dotnet publish -c Release
- cd ../..
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./docker_publish.sh
  on:
    branch: master
env:
  global:
  - secure: uy1Wz7pJyafmrCoZglkBD792CE2MN1EiiMdb1AdSjZC3GSWjBH5RiD/J7eK7hnQ+j1Mpsbqt+hrlPwKjaG9wXIJB3LAPmZaDPl6oQl6kCs5GAvmwdKEhLL4B8DcH8mDvCfHDwncM2IfZfxbOHrNwmn6cqxuhCSTOesMooCd+pDQiVwtJa/+Lot5C7H6B1FX8XP958chJjxoXl8KWN6S2AUXXngUdAHRNHDWl4NmFOJiN10qb5mSs2Ds9J6lNxtpYdr/n6MqqZIIGvhAEWu5QDPMB4aSjOfkaPDvr7GUjFc3xoBlmIn9ze67Wke+ohsRn2l0YB8aNM9dJIROTqTwoG9DZizFDPWt4F/m76qAv8yeI+xVvCRyfhHLZYesqTJBNzy0I/0Qw8noGdEbQXeqe7KOwUMhccvnZZ4TV8p4gqBgxwLsiphXyPMlTaENREY1SNQNdt1suyNHofWFzscGDG5n6yQCqcOHZPqkeYGFTqUgpEFamQ0VlYvL3AA+t8ryJ2pJtF9yRZ4uIcZHRhTlXrcvAu5Ggqn+1ncQ3Do7Ce6cdX9zgxJNaxetSPz4i1BbWDpn/DMp04xUFKI/gzTqKT4OKWwCB8pMd8dWDCiRwNNaGmcUCYQIW2NXBPgbZBOQAi5bnGmdDw0cCYlpL/ylsqzm/eNMq09hvh2BnVheLUqc=
  - secure: zKCKZqx9b9PXOFFCOks0aoTg9vGfKd5715gxn4IZ4E59KBTMAaX2OfwxjyApHPxYu0Nj7S4SKWCBa70MkF1YLeaYanC7MvdLdthF2i5p+vaVhCmTT9UUeEwLKLNiK8LwKfw5+8IoxI9iAtPXVO49pwi7eYQNwlN9hqrv2Dkr+l8fH5t+uDyDTdzJHsD+lGHZGqDPOnI/i4tmlaOGVeQH3lnFYaooVmOJJam09tXtDFET/Mys8hJgKXJy4RcRX2CkCg1KBsLbKqTmVGCUIH6GqklDV0WH2RLOjDEwiU7nyhpod233kwdIqRTbseAIShvpVC69+iptRM7B8i7hScQyPs9YENLLjqH4Mex53hApqv0sjPAJUIm7wzvdzzkWMIoRro+O264k9zjCz27W2c08xw47sN54YHkVMHzlWWEsItiOnhCwHljRWaeu/+UWsJ1FXzq/fzgmkyoi/9+F22wDS64UPr07tr1u+J3Y91RU08bvFg7cJa19GhaBA3xzytvkhLKQelJxOwKq1hyRT5GKx9NXerxJ6smcts7bg95n/xHIthOJ628gu9MPRPvG8qlv6xi0VR70A/SCv8L+1kEWbuvdFBS7JLbks0LbVYFP5Kdg3gHjaGf7kDGXXFUfbs/yHuAQKFxWz7fNqQKY82jz4gbdpbYTQ4dRQ4tOXtw1Jds=