language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

services:
  - docker

script:
- cd src/SpikeCore
- dotnet restore
- dotnet build -c Release
- dotnet publish -c Release
- cd ../..

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./docker_publish.sh
  on:
    branch: master

env:
  global:
  - secure: RgAG5mfVRfuWySMO73iamCTr2BjDu8J4i8uoGVG4CEAi/dbOaR0N9SM/koSAoE7/h7Wu9CDpUReYIuEscbwRjB0WwhuUDlSM/EMl0Ai7yjMAmEmmgcVUqsnlw5e27iQJdQhzHYuACpQHFSwQH4BfHhe17UCmKEeI9lmX541Iw3Q+UYSiQySD7f+BRnTFuROe+QaGclcbsnZnN5ChqWWoD3ty8jVajCf+0hIlKH2ZDzav/n68W+uhzv05trBnONOxfVQDGwLTRSQYpyL4Ci41epC6j3hyqH/nPqF/r8+8/bIx7SNB43ZlmMII0kMY7sg8miNBGIQRSzYrVO//l5zZWALZL/C1ucbVAOhjtcq6MmJo8UJ3A6Gxb1LLvi+6LmS5LNSMTAcxzqJoJ2/mtHFu7v9ka7/0a7SQUQmdci90mXROH7eR510Go2qpyp65wfhvYGbdJFoU61BebtPNPNhY83GqTLVnRBritiU8rtONFvCb8ZPM/5tO5Q06dh2V2jdBfCNNAmpC67YrUzp7CoHiPiNRDwzsKsECjYZIwQsQ0QFpoXpzGul8LSnpL5t2uffrSWrTzQoYdAW2J9AQUm0NKU+uFOugeQMqL0MLBmUhY/LsBZSmlvRZdt+nC2aU8tandV8XN7QAwhNvTFGhGdyoE0hIlzyvpLYcMWnjHq7Yn64=
  - secure: jnfGYNBgIax/gKboDN++0aO+Hd1eiDALg/O64Nijb++6UYMxXmR8mMJ8/tOP6TxLRwYET+EfsJw2Sl/Q20nHPaFPZYLr1Uug1kUcp+T0FYq0gq9ewbjAWIXXuxGHXAfPRNwxz4bBmZIdlUpeorJlDN3bMQgpTkeGZDxlEGYcrmG0p+wBy2dl554fF2GM5GVNrUw8c9fVHo5Tbd82iXa5AYl47JeoCZnkyxKHu0Ocqbyxvz5QKk6qvODTtVueixOh6jXERZXw3XeVWoqWY+EYdRgKvmwBvHCHd4JnYE2hudkKqJQsimnb9x48mN5QTXXaACuUpoJxie5WFWdil8i3qfHzuniMvHXn4B/UqJSlg/FODVyytMhjKNWZC+78aTQacPiZ5KQWxRI1mN6qEp2kdxc1ygfqzk4VpE1yBa3xz6a35+R79AwgqG2qvbQGOGqRosFIXlOEB95Vr7pRJJVY4bXIBsuOe0/TQuUCYHs1MIqFFpGLRqxM/7oPiXoWE4B2TSI8CTfeyb+PTS8BCR6x1UvKL2HyUjbZluGJBGbegS0wDk839adYLwAGxojCZkzzyIAn5ic9q1OQ6I8dWgPS0tCWY+qP1L3w/LdtZLZqOCUP4L2CSL+23/nlL76uE4uKxHQ9hjKiEtlo3RAP/R/QaHc91SKe6UaJ6UOeJjyY6iE=
